name: Build on Windows

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step clones the Git repository

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          cd ..
        shell: powershell

      - name: Install dependencies with vcpkg
        run: vcpkg\vcpkg install
        shell: powershell

      - name: Configure and build with CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=D:/a/MiniCraft/MiniCraft/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build .
        shell: powershell
